name: 'Suggest Labels'
description: 'Suggests labels for open issues using AI.'
branding:
  icon: tag
  color: purple
inputs:
  repo:
    description: "The repo with the issues that need label suggestions."
    required: false
    default: ${{ github.event.repository.name }}
  owner:
    description: "The repo owner's user ID."
    required: false
    default: ${{ github.repository_owner }}
  token:
    description: "Access token that can access the issues on the repo."
    required: false
    default: ${{ github.token }}
  api-key:
    description: "OpenAI API access key."
    required: true
  endpoint:
    description: "OpenAI endpoint for accessing the model."
    required: true
  deployment-id: 
    description: "The deployment ID of the OpenAI model."
    required: true
runs:
  using: 'node16'
  main: 'index.js'